version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: Install aws sdk
          command: 'sudo pip3 install boto3'
      - deploy:
          name: Deploy lambda to aws
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              python3 deploy.py
            fi