version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: Print linux version
          command: 'cat /proc/version'
      - run:
          name: Install serverless
          command: 'sudo npm install -g serverless'
      - deploy:
          name: Deploy lambda to aws
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              serverless deploy -v
            fi